package com.smollvile.gpsweather.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.smollvile.gpsweather.dao.Story;

import com.smollvile.gpsweather.dao.StoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storyDaoConfig;

    private final StoryDao storyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storyDaoConfig = daoConfigMap.get(StoryDao.class).clone();
        storyDaoConfig.initIdentityScope(type);

        storyDao = new StoryDao(storyDaoConfig, this);

        registerDao(Story.class, storyDao);
    }
    
    public void clear() {
        storyDaoConfig.clearIdentityScope();
    }

    public StoryDao getStoryDao() {
        return storyDao;
    }

}
